### ISSUE TITLE
When Create-React-App built, Map style doesn't work.

### ISSUE THREAD

**Issue by belopot** [visgl/react-map-gl#1420] opened 2021-03-29 06:16 UTC
Hi

I created a Create-React-App and added the StaticMap.

StaticMap and Mapbox's Token in .env file
![image](https://user-images.githubusercontent.com/46432435/112793358-2c8b7180-9033-11eb-96d1-af510c459163.png)
![image](https://user-images.githubusercontent.com/46432435/112793374-34e3ac80-9033-11eb-9692-68d23e05047a.png)

When run "yarn start", It works well. 
![image](https://user-images.githubusercontent.com/46432435/112794200-86d90200-9034-11eb-83c3-a0ec03066702.png)

However, when building the app with "yarn build", it doesn't work.
![image](https://user-images.githubusercontent.com/46432435/112794272-99ebd200-9034-11eb-87bf-4957550f01e7.png)

Can you fix this issue?

**Comment by kylebarron** [comment] 2021-03-29 06:42
duplicate of https://github.com/visgl/react-map-gl/issues/1266

**Closed by kylebarron** 2021-03-29 06:43 UTC
Labels: bug
