### ISSUE TITLE
react build problem

### ISSUE THREAD

**Issue by qiaoxin136** [visgl/react-map-gl#1300] opened 2021-01-16 01:38 UTC
when i do "yarn start", everything looks good. 

![image](https://user-images.githubusercontent.com/44871863/104793567-365e4200-5771-11eb-84e2-806f8668871a.png)

but after i do "yarn build" and upload the build file to Microsoft Azure, the map screen disappeared.
I tested on AWS S3, the result is the same. 

![image](https://user-images.githubusercontent.com/44871863/104793616-79b8b080-5771-11eb-8a4f-df0d1e2800aa.png)

I think this is a build problem. But i do not know how to resolve it. Can anyone give me a direction how to fix it? Thanks.

**Comment by kylebarron** [comment] 2021-01-16 02:04
Duplicate of https://github.com/visgl/react-map-gl/issues/1266

**Closed by kylebarron** 2021-01-16 02:04 UTC
