### ISSUE TITLE
create-react-app (react-scripts 4.0.1) not working with react-map-gl 6.0.3

### ISSUE THREAD

**Issue by marc-slingshot** [visgl/react-map-gl#1292] opened 2021-01-11 18:22 UTC
I am having trouble getting react-scripts and react-map-gl working together in the production build.  It works when running `npm run start`, but the result of `npm run build` gives errors.

I have a repo showing the issue here - https://github.com/marc-slingshot/create-react-app-with-react-map-gl

Downgrading to 5.2.12 works.  Could this be related to mapbox-gl v2?  I noticed similar (but not exact) problems on this older issue thread - https://github.com/visgl/react-map-gl/issues/176

### Steps to reproduce
1. clone this repo `git clone https://github.com/marc-slingshot/create-react-app-with-react-map-gl.git`
1. add mapbox API token to `.env.local`
```
REACT_APP_MAPBOX_TOKEN=<your mapbox token>
```
1. `npm i`
1. `npm run build`
1. `npm i -g serve`
1. `npx serve -s build`
1. open up http://localhost:5000, open up dev tools, notice errors

I get the following error:
```
Uncaught ReferenceError: y is not defined
    at a915e7a2-d12d-45dc-b9bc-45bf5baa8c10:1
    at a915e7a2-d12d-45dc-b9bc-45bf5baa8c10:1
    at a915e7a2-d12d-45dc-b9bc-45bf5baa8c10:1
```

**Comment by marc-slingshot** [comment] 2021-01-11 18:24
hrm.... looks like it's mapbox-gl upstream then according to this other open issue - https://github.com/visgl/react-map-gl/issues/1266

**Comment by Pessimistress** [comment] 2021-01-11 18:28
Duplicate of #1266

**Closed by Pessimistress** 2021-01-11 18:28 UTC
