### ISSUE TITLE
[Bug] Map loading issue on resizing width

### ISSUE THREAD

**Issue by neelduttahere** [visgl/react-map-gl#2385] opened 2024-05-06 11:04 UTC
### Description

When resizing width after panning, the map doesn't load, until map is moved. For better context refer to attached video below: (T1 is clicked to expand and collapse the sidebar)

https://github.com/visgl/react-map-gl/assets/59992993/a56ecdf7-182d-46f7-b108-7bea79945b77

This is specifically happening when app is designed in a sidebar-body layout, where sidebar is expandable/collapsible (not that it matters, but can be reproduced if parent div is programatically resized as well).

### Expected Behavior

Map should load as usual, despite parent div width being resized.

### Steps to Reproduce

https://codesandbox.io/p/sandbox/react-map-gl-width-error-9c9stk?file=%2Fsrc%2FApp.js%3A20%2C40

You can reproduce this issue using the sandbox code. Watch below video to reproduce this from UI.

1. Expand sidebar by clicking T1
2. Move map a bit towards left of screen
3. Click again on T1 to collapse sidebar

https://github.com/visgl/react-map-gl/assets/59992993/5b13932c-9a10-4678-9716-a500ec91ebe1

### Environment

- Framework version: react-map-gl@7.1.7
- Map library: mapbox-gl@3.3.0
- Browser: All browsers
- OS: Any OS same behaviour

**Comment by Pessimistress** [comment] 2024-05-06 12:36
Duplicate of #2338

**Closed by Pessimistress** 2024-05-06 12:36 UTC
Labels: bug
