### ISSUE TITLE
markers overlapping popup

### ISSUE THREAD

**Issue by sk-ismail** [visgl/react-map-gl#1532] opened 2021-07-19 08:28 UTC
#### Description

Markers are overlapping popup

I have set z-index but still the problem isn't solved

check my site for more details:- https://covid19-data-007.netlify.app (check the issue in visuals section)

![marker](https://user-images.githubusercontent.com/42185028/126127370-378af8f6-4ae6-4232-bb76-73da168189f0.png)

#### Environment :

- Library Version:react-map-gl 5.2.5
- React Version: react 17.0.2
- OS: Linux Ubuntu 20.04

**Comment by Pessimistress** [comment] 2021-07-19 11:54
Please provide code to reproduce.

**Comment by sk-ismail** [comment] 2021-07-20 07:30
> Please provide code to reproduce.

Code :- https://codesandbox.io/s/vigilant-lewin-54pnc

**Comment by nardove** [comment] 2021-07-21 19:52
How about setting `sortByDepth={true}` on the Popup? (which is pretty much be the same as rendering the Popup after the Markers) The problem I see with that is that the red marker will get obscured by the Popup, I wonder if there is a way to offset the Popup by detecting its position? that way problem solved, I'm having this issue myself

**Comment by Pessimistress** [comment] 2021-07-21 20:02
@sk-ismail Your Popup component has `className="popupCard1"`.  If you add 

```css
.popupCard1 {
  z-index: 1000;
}
```

to styles.css you can see that it's on top.

**Comment by nardove** [comment] 2021-07-21 20:07
That does solve the problem as well, but the overlapping occurs as shown in my last picture, I wonder if there is a way to detect that the Popup is at the top and therefore offset its position accordingly?

**Comment by Pessimistress** [comment] 2021-07-26 18:47
@nardove There is no automatic detection because each marker/popup is rendered independently. To explore other options you may create a thread in Discussions.

I'm closing this issue since it is not a bug.

**Closed by Pessimistress** 2021-07-26 18:47 UTC
