### ISSUE TITLE
Zooming is very slow after upgrade

### ISSUE THREAD

**Issue by daniela-green** [visgl/react-map-gl#1316] opened 2021-02-01 17:22 UTC
After upgrade from 5.2.12 to 5.3.1, the zoom is very very slow.
Happens also on your examples site:
https://visgl.github.io/react-map-gl/examples/layers

**Comment by Pessimistress** [comment] 2021-02-01 18:38
What OS/browser are you using? Can you try `scrollZoom={{smooth: false}}`?

**Comment by nertzy** [comment] 2021-02-01 19:52
`scrollZoom={{smooth: false}}` fixes the problem for us.

We have seen the issue on:
- macOS 11.1 / Firefox Developer Edition 86.0b4 (64-bit)
- macOS 11.1 / Chrome 88.0.4324.96 (Official Build) (x86_64)

**Comment by kentongray** [comment] 2021-02-01 20:06
I am also seeing the same thing after upgrading.. unfortunately the typescript types don't allow the scroll zoom props so I can do a PR to allow that

**Comment by kentongray** [comment] 2021-02-01 20:07
also just a note on this the issue is much more pronounced using a trackpad vs a wheel, probably due to frequency the scroll events fire

**Comment by Pessimistress** [comment] 2021-02-01 20:09
Thanks maybe enabling smooth zoom was premature. I can revert the default back to what it was and make this an opt-in feature instead.

**Comment by daniela-green** [comment] 2021-02-02 10:57
@Pessimistress
Similar to whats written above, im using:
**macOs 10/ Chrome 88**

Also, im using typescript and dont have this prop type, will wait for @kentongray PR.

Thanks!

**Comment by Pessimistress** [comment] 2021-02-02 19:00
Fixed in 5.3.3/6.1.3

**Closed by Pessimistress** 2021-02-02 19:00 UTC

**Comment by daniela-green** [comment] 2021-02-02 19:12
@Pessimistress indeed all works well with 5.3.3
Thanks!
