### ISSUE TITLE
Event handling with conditional elements in Popup

### ISSUE THREAD

**Issue by garretteklof** [visgl/react-map-gl#1433] opened 2021-04-13 21:24 UTC
#### Description

Popups with conditional elements (e.g. nested modal triggered by a button click inside Popup container) propagate events to Map when`captureClick={true}`.

#### Repro Steps
[Here is a codesandbox](https://codesandbox.io/s/gallant-jackson-yp0u8?file=/src/App.js) that illustrates the behavior. I've tried `e.stopPropagation()` however, I don't think event handling is through React so it can't stop it. The only way that I found is to stop the event with `MapContext` and `eventManager` (i.e. `context.eventManager.once("click", e => e.stopPropagation(), reactEvent.target)` 

Is there a better way to handle these cases? Am I overlooking something simple?

**Comment by piyush-wal** [comment] 2021-04-25 15:59
hey @garretteklof 
I am using a dropdown in popup so i set 'capturescroll={true}' in popup
but this is effecting the drop-down option scroll also i want to scroll the drop-down option menu to see more options but the scroll is not working for dropdwon also 
Can you suggest me how can i achieve it

**Comment by garretteklof** [comment] 2021-04-27 04:01
@piyush-wal if you have a minimal reproducible code sandbox I could probably help you, but it's tough to say without seeing code. I have scrollable components in Popups with no issues. Off the top of my head (at risk of sounding obvious) of course make sure the component itself is scrollable (via overflow) and remember the prop is camel case (captureScroll).

**Comment by Pessimistress** [comment] 2022-03-02 18:17
Closing this because it cannot be reproduced in v7.

**Closed by Pessimistress** 2022-03-02 18:17 UTC
Labels: bug
