### ISSUE TITLE
dragPan doesn't work after zooming

### ISSUE THREAD

**Issue by Florian-crg** [visgl/react-map-gl#1502] opened 2021-06-18 16:43 UTC
#### Description

The map option  dragPan: false doesn't work after zooming on the map

#### Repro Steps

Set dragPan to false, if you're on desktop scroll on the map which will zoom, then drag the map.

#### Environment (please complete the following information):

- Library Version: [react-map-gl 6.1.15]
- React Version: [react 17.0.2]
- Browser Version: [91.0.4472.106 ]
- OS: [Mac OS X 11.3.1]

**Comment by Pessimistress** [comment] 2021-06-18 17:43
The prop seems to be working as expected with https://visgl.github.io/react-map-gl/examples/interaction. Please create a CodeSandbox that reproduces your issue.

**Comment by Pessimistress** [comment] 2021-06-25 19:16
Closing - unable to reproduce

**Closed by Pessimistress** 2021-06-25 19:16 UTC
Labels: bug
