### ISSUE TITLE
Map and markers misalignment in Chrome

### ISSUE THREAD

**Issue by danton004** [visgl/react-map-gl#877] opened 2019-09-02 06:41 UTC
Hi all,

I´m showing some customized markers on a react-map-gl map. However, the markers and the map are misaligned when redered in Chrome. The markers seem to be in the right position but the map itself is streached vertically. 

I have also noticed that it happens when the screen height is larger than aprox 1500px, with height under 1500px the map and the markers are shown correctly. 

This only happens in Chrome in Android, for instance,  on Desktop, Iphones or other browser in Android (Firefox, Edge) the map is shown correctly.

I´m using version 4.1.7, however, the issue also happens in the latest version.

Here are some screenshots

Chorme
![Screenshot_2019-08-30-07-22-48-799_com android chrome](https://user-images.githubusercontent.com/49440121/64094542-682d5f00-cd5c-11e9-8771-d26806249ae8.png)

Firefox
![Screenshot_2019-08-30-07-24-11-026_org mozilla firefox](https://user-images.githubusercontent.com/49440121/64094533-65326e80-cd5c-11e9-9f95-a11a784161ce.png)

Any ideas what could be happening?

Thanks,

David

**Comment by Pessimistress** [comment] 2021-03-01 17:12
Closing since this issue was referring to an outdated version of react-map-gl. Open a new issue if it can be reproduced on the latest release.

**Closed by Pessimistress** 2021-03-01 17:12 UTC
