### ISSUE TITLE
Bug: m is not defined error - Map css will not appear in production for latest version

### ISSUE THREAD

**Issue by abrown945** [visgl/react-map-gl#1275] opened 2020-12-21 20:48 UTC
The map css for the styles would not be visible during production. 

![image (2)](https://user-images.githubusercontent.com/23192489/102820582-7f55ed00-43a3-11eb-96ec-975fb144cbc9.png)

The only map style that was visible was the satellite view because it did not have any css

**Error** 

![image](https://user-images.githubusercontent.com/23192489/102820336-166e7500-43a3-11eb-822a-c39b1161ebb8.png)

There were no errors evident in the console when the app was in development mode. The bug was only visible in production and the same for the error as a consequence.

Our error was resolved when we reverted to an older version (5.2.9 specifically).

**Comment by abrown945** [comment] 2020-12-21 20:49
Error said "m is not defined" and pointed to the code above. No other hints via text were given.

**Comment by Pessimistress** [comment] 2020-12-21 21:28
Duplicate of #1266

**Closed** 2020-12-21 21:28 UTC

**Comment by db926** [comment] 2020-12-23 18:10
Same issue

![image](https://user-images.githubusercontent.com/51146410/103025637-37d48a00-4578-11eb-9b98-a0cc7b9ba761.png)

Production View

![image](https://user-images.githubusercontent.com/51146410/103025659-41f68880-4578-11eb-8694-44e2f00067f1.png)

**Comment by Lemorz56** [comment] 2021-01-10 15:46
I also have the same issue. Anyone has a fix?

**Comment by kylebarron** [comment] 2021-01-11 00:18
This is a duplicate of #1266. Refer to that issue.
