### ISSUE TITLE
react-map-gl with Mapbox v2 fails

### ISSUE THREAD

**Issue by zanemountcastle** [visgl/react-map-gl#1284] opened 2021-01-03 00:56 UTC
After running a Webpack build (with `create-react-app`), I get the following error in the browser:

```
Uncaught ReferenceError: y is not defined
```

This is a [known](https://github.com/mapbox/mapbox-gl-js/issues/10173) issue with `mapbox-gl` using the recent Mapbox v2 release, which can be resolved for the time being using:

```
mapboxgl.workerClass = require("worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker").default;
```
However, when I migrated from `mapbox-gl` to `react-map-gl`, the error reappeared and the fixes suggested [here](https://github.com/mapbox/mapbox-gl-js/issues/10173) don't seem to work.

`react-map-gl` works just fine when run locally without building.

**Comment by kylebarron** [comment] 2021-01-03 02:02
duplicate of https://github.com/visgl/react-map-gl/issues/1266

**Closed** 2021-01-03 02:03 UTC

**Comment by sanchezzzs** [comment] 2022-09-14 13:51
Editing package.json worked for me. I'm using maplibre-gl
"browserslist": {
    "production": [
      "defaults",
      "not ie 11"
    ],
  },

check this: https://docs.mapbox.com/mapbox-gl-js/guides/install/

**Comment by franciscocaballero** [comment] 2023-01-20 22:52
> Editing package.json worked for me. I'm using maplibre-gl
> 
> ```
> "browserslist": {
>     "production": [
>       "defaults",
>       "not ie 11"
>     ],
>   },
> ```
> 
> check this: https://docs.mapbox.com/mapbox-gl-js/guides/install/#targeting-transpilation-to-es6-with-browserslist

Thank you! This also worked for me.
