### ISSUE TITLE
maps doesn't appear after build the static file react.js

### ISSUE THREAD

**Issue by balbaal** [visgl/react-map-gl#1326] opened 2021-02-03 15:34 UTC
on development mode, that map running properly
![Screen Shot 2021-02-03 at 23 31 50](https://user-images.githubusercontent.com/20864870/106769726-3a96c480-6678-11eb-8372-a269e74d33ea.png)

but after i'm build static file react (npm run build) and running it. that map doesn't appear
![Screen Shot 2021-02-03 at 23 32 15](https://user-images.githubusercontent.com/20864870/106769841-5ef2a100-6678-11eb-8b7a-a22e1394deec.png)

**Comment by kylebarron** [comment] 2021-02-03 16:22
Duplicate of https://github.com/visgl/react-map-gl/issues/1266

**Closed by kylebarron** 2021-02-03 16:22 UTC
