### ISSUE TITLE
FullscreenControl: no way to return to original size

### ISSUE THREAD

**Issue by frank-unovica** [visgl/react-map-gl#1605] opened 2021-11-05 09:47 UTC
#### Description

The FullscreenControl does not restore the original viewport w/h on return (as I would expect by default), and has no documented onViewportChange property or other way to detect fullscreen state. The one example that features it (markers & popups) has w/h hardcoded to 100% and therefore ignores the faulty viewport size. You should be able to reproduce it by removing that hardcoding. Wrapping a div also does not force its child to shrink down, at least not without guru level css.

Another issue is that capturePointerMove={true} does not prevent panning the map while holding down the FullscreenControl. For NavigationControl and GeolocateControl this does work.

Also, in NavigationControl, the compass icon is not visible and I'm not able to drag the button to change orientation/pitch as I would expect (with capturePointerMove={true} or false).

#### Environment (please complete the following information):

- Library Version: [e.g. react-map-gl 6.1.10]
6.1.17
- Mapbox Version: [e.g. mapbox-gl 2.1.1]
maplibre-gl 2.0.0-pre.5
- React Version: [e.g. react 17.0.1]
17.0.2
- Browser Version: [e.g. Chrome 88.0]
Chrome 95
- OS: [e.g. Mac OS X 11.2]
Ubuntu 20.04.3 LTS

#### Logs

No relevant logs, except that the viewport remains set to the screen resolution

**Comment by frank-unovica** [comment] 2021-11-05 10:45
Maplibre uses 'mapboxgl-ctrl-compass' css class rather than 'mapboxgl-ctrl-compass-arrow' as hardcoded in react-map-gl

**Comment by Pessimistress** [comment] 2021-11-06 00:21
The map component is stateless. `width` and `height` numbers from the `onViewportChange` callback is the *result* of the width and height props that you provide (what you referred to as "hard coded"). If you just blindly feed them back to the component then yes, you will be stuck in the situation where you cannot "go back" to where you were.

> capturePointerMove={true} does not prevent panning the map while holding down the FullscreenControl.

The purpose of `capturePointerMove` is to block `onPointerMove` event. Use `captureDrag` to block panning. This is explained in the documentation:

http://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control#capturedrag

> Also, in NavigationControl,

Duplicate of https://github.com/visgl/react-map-gl/issues/1467

**Closed** 2022-01-03 07:44 UTC
Labels: bug
