### ISSUE TITLE
Error: There is no source with id.

### ISSUE THREAD

**Issue by ats1999** [visgl/react-map-gl#1281] opened 2020-12-30 12:44 UTC
I got this error too many times.
`Error: There is no source with id.`
I have some source and layer like this
```js
data.map(data=>{
  return <Source {...props}>
                    <Layer {...props}/>
          </Source>
})
```
Here i am removing all sources and layers from the map on some event, say click on a button. Then again i am adding those sources and layers to map on some action.

While removing I'm getting this error.

**Comment by Pessimistress** [comment] 2021-01-06 05:36
Please create a CodeSandbox that reproduces your issue.

**Comment by ats1999** [comment] 2021-01-07 14:08
this error is not being reproduced, because it doesn't occur every time on the sandbox. I have a private project, where i am using **react-map-gl** and **deck.gl** to display icons and lines. Here, i used `deck.gl` as a first child of `react-map-gl`. `Deck.gl` provides a way to render the line in perspective view. 

I have a `3d` button, when it is on, then i am rendering `deck.gl` layers, and when it's off then I'm rendering `react-map-gl` layers. 

This is where the problem comes when i switch from `react-map-gl` to `deck.gl`.

### Although, error is not being reproduced, but if you agree then i can share my PC screen.

> I would be happy to help you

**Comment by Pessimistress** [comment] 2021-01-12 08:46
Closing - cannot reproduce

**Closed by Pessimistress** 2021-01-12 08:47 UTC
