### ISSUE TITLE
[Bug] error e.originalEvent not found in nextJS

### ISSUE THREAD

**Issue by AlirezaNikkhah1375** [visgl/react-map-gl#1889] opened 2022-06-11 16:58 UTC
### Description

when i use e.originalEvent.stopPropagation(); in popup/marker example it gives me error " originalEvent " not found and i solved it just by removing "originalEvent" function and it worked well 

### Steps to Reproduce

null

### Environment

- Framework version: nextJs
- Map library:
- Browser: firefox
- OS: linux

**Comment by luismiddleton** [comment] 2022-06-12 06:07
I'm unable to replicate this error. Can you state which version of Next you are using, as well as the package version of `react-map-gl` ?

**Comment by AlirezaNikkhah1375** [comment] 2022-06-13 08:53
"next": "12.1.6" and "react-map-gl": "^7.0.15"

**Comment by Pessimistress** [comment] 2022-08-10 14:05
Closing because there are no steps to reproduce. This issue also refers to example code, not the library itself. Please use discussions for help with your own application.

**Closed by Pessimistress** 2022-08-10 14:05 UTC
Labels: bug
