### ISSUE TITLE
Error: @math.gl/web-mercator: assertion failed.

### ISSUE THREAD

**Issue by nonoumasy** [visgl/react-map-gl#1237] opened 2020-11-26 02:00 UTC
Ok, so i've gone over this web assertion problem over and over. I read all the comments here so I must be looking at this too closely and too long. Can someone pls let me know what I am doing to cause this web-assertion error?

I am trying to set it up so that the map will show the bounds of all lat/lon points added to the map.So I put the lon and lat values into an array, find the min and max values and then use these as corner coordinates for fitBounds method on  WebMercatorViewport.

Now, everything is works when I hard code the coordinates on fitBounds method like this...
<img width="771" alt="Screen Shot 2020-11-25 at 6 00 12 PM" src="https://user-images.githubusercontent.com/6312676/100299261-15832880-2f48-11eb-94b7-67df17ce8dd4.png">

but when I use a variable ('cornersLongLat') which is the same as those hard coded values, it throws this error...
![Screen Shot 2020-11-25 at 5 53 27 PM (2)](https://user-images.githubusercontent.com/6312676/100298900-25e6d380-2f47-11eb-943b-85b50f9ecd84.png)

Just some notes:

1. I made sure to convert the coordinates to Number.
2. when I console.log the coordinates they are exactly the same as the number I hard coded to fitBounds which makes the code work
![Screen Shot 2020-11-25 at 3 38 00 PM](https://user-images.githubusercontent.com/6312676/100298929-372fe000-2f47-11eb-93ee-2bd0580894fa.png)
3. The fitBounds accepts [[number, number],[number, number]] and that is the shape of the variable I am passing.
4. I tried different configuration of latitude and longitude
5. I tried using [cornersLongLat[0], cornersLongLat[1]]. This didn't work either.

Here is my code:

```

const getBounds = () => {
        // Calculate corner values of bounds
        const eventLongitude = props.props.event && props.props.event.map(item => Number(item.eventLongitude))
        const eventLatitude = props.props.event && props.props.event.map(item => Number(item.eventLatitude))

        const cornersLongLat = [
            [Math.min.apply(Math, eventLongitude), Math.min.apply(Math, eventLatitude)],
            [Math.max.apply(Math, eventLongitude), Math.max.apply(Math, eventLatitude)]
        ]

        // Use WebMercatorViewport to get center longitude/latitude and zoom
        const viewport = new WebMercatorViewport({ width: 800, height: 600 })
            .fitBounds([[12.3, 31.7683], [35.2137, 43]], { padding: 100 }) 
            // .fitBounds(cornersLongLat, { padding: 100 })


        const { longitude, latitude, zoom } = viewport
        return { longitude, latitude, zoom }
        } 

    const bounds = getBounds()

``` 

What I'm thinking at this point is some async error, but I don't think so. I think it's something simpler. Why would fitBound not accept my variable?

**Comment by kylebarron** [comment] 2020-11-26 05:16
`Math.min.apply(Math, 20)` gives a TypeError in the console for me.

**Comment by nonoumasy** [comment] 2020-11-26 07:22
it has to be an array...

const eventLongitude =[20, 30, 40]
Math.min.apply(Math, eventLongitude)

or even...

const eventLongitude =[20]
Math.min.apply(Math, eventLongitude)

It's looking for the minimum value from an array of values.

**Comment by utb2017** [comment] 2020-11-27 21:55
So this WebMercatorViewport is very sensitive.  

This works.
`const {longitude, latitude, zoom} = viewport.fitBounds(bounds, { padding: 20 }); `

This throws an assertion error.
`const {longitude, latitude, zoom} = viewport.fitBounds(bounds, { padding:  50 });`

Does the excess padding cause a zoom error or something?

This also throws an assertion error.
const {longitude, latitude, zoom} = viewport.fitBounds(bounds, { padding: 40, offset: [0,-20] });

And this throws an assertion error.
const {longitude, latitude, zoom} = viewport.fitBounds(bounds, { padding: {top: 303, bottom: 303, left: 14, right: 14} });


Seems like I'm missing something? 
Is it just trial and error with this WebMercatorViewport, and taking what you can get?

**Comment by Pessimistress** [comment] 2020-11-27 22:57
Why would you want to run this on the server side? It doesn't make sense to call `fitBounds` before you know the size of your viewport.

You can subscribe to [onResize](http://visgl.github.io/react-map-gl/docs/api-reference/static-map#onresize) for the actual viewport size.

**Comment by utb2017** [comment] 2020-11-27 23:18
@Pessimistress  I am not a pro at server-side apps yet. So I don't know the best way to answer your question other than, I'm not trying to run this on server-side. I just know that this will throw an error when loading, and Im not looking for max screen width.

```
    const viewport = new WebMercatorViewport({
      width: window.innerWidth,
      height: window.innerHeight,
    });
```

I created a useEffect that will work to get my map container size.

```
  const {width, height} = useWindowSize()
  const [mapSize, setMapSize] = useState({width, height})

  useEffect(() => {
    if(width<=767){
      setMapSize({width,height:420})
    }else if ((width>767) && (width<919)) {
      setMapSize({width:(width-350),height:height})
    }else if ((width>=919)) {
      setMapSize({width:(width-(350+256)),height:height})
    }else if (width >= 1366){
      setMapSize({width:(width-(350+460)),height:height})
    }else {
      setMapSize({width,height})
    }
  }, [width, height]);
```

Then I can apply the values like this. 

```
        const { height, width } = mapSize
        viewport = {...view, ...{height, width}}
        viewport = new WebMercatorViewport(viewport)
```


I will look into this onResize subscription, but my map is set at 100% and doesn't seem to change width or height after the page is loaded.

**Comment by nonoumasy** [comment] 2020-11-28 04:48
Going back to my original posting, I could use @turf/bbox to calculate the bounding box of my lat and lon values. However I have these as strings now and NOT GeoJSON which turf expects, so I would have to refactor my Mongo schema to geoJSON which I was planning on doing but just not now. I think once I do that, using turf js would be far the best way to implement my feature.
However, it is still strange how hard coding the values works and using a variable does NOT. There is no type issue that I can see and the values are identical when logged.

**Comment by Pessimistress** [comment] 2020-12-01 16:23
Closing - from what you described the issue is not in react-map-gl.

**Closed by Pessimistress** 2020-12-01 16:23 UTC

**Comment by abettermap** [comment] 2021-04-17 18:06
For anyone like me whose map does not occupy the full window height and width, if you have access to the `map` object you can grab its dimensions and use those instead:

```js
let padding = 20

const bounds = [ [-74.05, 40.598], [-73.767185, 40.862] ] // or whatever
const { offsetHeight: height, offsetWidth: width } = map.getContainer()

// If you have some media queries where the map size changes, adjust these
// if (breakpoint === 'mobile' || breakpoint === 'tablet') padding = 25
// else padding = 100

// You could certainly improve on this, but I found it easiest to simply jump
// ship and set the padding to nothing instead of recalculating what would fit.
if (padding * 2 > height || padding * 2 > width) padding = 0

// Use it however you need to
const webMercViewport = new WebMercatorViewport({
  width,
  height,
}).fitBounds(bounds, { padding })
```

I took the lazy way out and set padding to `0` there, but after seeing this error for months it was just a relief for anything but that!

**Comment by TGChrisRArendt** [comment] 2021-08-06 19:46
```
if (padding * 2 > height || padding * 2 > width) 
  padding = height > width ? height / 2 : width/2;
``` 
right?

**Comment by abettermap** [comment] 2021-08-08 23:58
> ```
> if (padding * 2 > height || padding * 2 > width) 
>   padding = height > width ? height / 2 : width / 2;
> ```
> 
> right?

Not sure. I might be reading it incorrectly but I don't see how the relationship between height and width would guarantee that there is enough map space available for `height / 2` or `width / 2` padding. It seems like that could potentially lead to the same error as before but again, I may be misunderstanding.
