### ISSUE TITLE
Upgrading version from 6.0.2 to 6.1.3 throws error on transition

### ISSUE THREAD

**Issue by intelcoder** [visgl/react-map-gl#1327] opened 2021-02-03 19:17 UTC
I was really excited to see you guys added eventRecognizerOptions to the new version.

However, I am encountering a few problems or bug.

Firstly, old version(6.0.2) did not fires viewportChange event when display css change from display none to block so I was able to not unmounting map component and keep using it. However, the new version fires viewportChange on display none to block which changes map bounds.
Is this intentional? 

Secondly, when I add/remove new FlyToInterpolator() to transitionInterpolator, the map often throws longitude is not defined. However,  longitude is always there.

**Comment by Pessimistress** [comment] 2021-02-03 20:07
From 6.0 to 6.1 we switched from `react-virtualized-auto-sizer` to using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver). There might be minor differences in when the resize events are fired.

Regarding FlyToInterpolator, please create a CodeSandbox that reproduces your issue.

**Comment by intelcoder** [comment] 2021-02-03 20:46
Then, you think it is correct to fire viewportChange on display status change?

I created codesandbox. 
https://codesandbox.io/s/unruffled-wilbur-r5mt3?file=/src/App.js

It appear to be crashing when map is not visible and viewport keep updating with FlyToInterpolator. 

You can hide the map then click on the change location button few times.

**Comment by Pessimistress** [comment] 2021-02-04 01:29
Looks like the `FlyToInterpolator` yields `longitude: NaN` when width/height are 0 at t=0. I will look into this. Meanwhile you can easily work around it by not triggering a new transition when the map is hidden.

> it always go back to the initial map center with zoom

This was a bug fixed in 6.1.4.

**Comment by intelcoder** [comment] 2021-02-04 14:19
Yes, I am doing that for now. Cannot wait for 6.1.4 version.

**Comment by Pessimistress** [comment] 2021-02-07 18:17
A fix for height:0 handling is landed in 5.3.5/6.1.5.

**Closed by Pessimistress** 2021-02-07 18:17 UTC

**Comment by pcwa-ahendricks** [comment] 2021-02-18 22:33
Even with version 6.1.8 I have to use something like the following in order to prevent this error:

```
 const [ready, setReady] = useState(false)

  useEffect(() => {
    setTimeout(() => setReady(true))
  }, [])

...

setViewport((prev) => ({
      ...prev
      transitionDuration: ready ? 1500 : undefined,
      transitionInterpolator: ready ? new FlyToInterpolator() : undefined,
      transitionEasing: ready ? easeCubic : undefined
    }))
```

**Comment by Pessimistress** [comment] 2021-02-19 01:54
@pcwa-ahendricks The bug reported by this issue was already resolved. If you are experiencing a similar problem, please create a new issue with a CodeSandbox to reproduce it.
