### ISSUE TITLE
[Bug] Source/Layer does not work within MapProvider

### ISSUE THREAD

**Issue by tordans** [visgl/react-map-gl#1946] opened 2022-08-09 15:07 UTC
### Description

I am following the `MapProvider` example from https://github.com/visgl/react-map-gl/tree/7.0-release/examples/get-started/hook / https://visgl.github.io/react-map-gl/docs/api-reference/use-map which does work.

I am trying to put a component that handles adding all sources/layer inside the MapProvider.

Example:
```
        <MapProvider>
          <Map />
          <Sources />  {/* <- does not work, needs to be inside <Map> */}
        </MapProvider>
```

Inside the `<Sources>` Component I have multiple `Source > Layer` "call".

However, that does not work, since source.js does not get access to the map.

| Screenshot |
|---|
| <img width="804" alt="image" src="https://user-images.githubusercontent.com/111561/183685118-54a65113-e16b-4229-861e-e93877d52af2.png"> |

It looks like, there is no way to provide the map to [source](https://visgl.github.io/react-map-gl/docs/api-reference/source) via props and `useMap()` or any other way.

### Expected Behavior

I expect a prop `map={map}` from `const {map} = useMap()` on `<Source>`. `<Layer>` will probably get the map context from its `<Source>` parent.

Or, alternatively, a way to provide the needed useContext-context to Source and Layer.

### Steps to Reproduce

1. Follow https://github.com/visgl/react-map-gl/tree/7.0-release/examples/get-started/hook
2. Create a components Sources
3. Add Source+Layer in this component, access the map via useMap
4. Add the Sources-Component on the same level as `Map` inside a `MapProvider`

### Environment

- Framework version:  "react-map-gl": "^7.0.17",
- Map library: "maplibre-gl": "^2.1.9",
- React 17

**Comment by Pessimistress** [comment] 2022-08-09 15:23
Source is not supposed to work out of a Map. A MapProvider can wrap multiple Map instances, but a Source can only be attached to one.

**Comment by tordans** [comment] 2022-08-09 15:58
> A MapProvider can wrap multiple Map instances, but a Source can only be attached to one.

That is true for many action that I can use with `useMap`, right? What I was expecting is, that I can provide the map to Source by using useMap the same way I tell a click event which map to "use".

**Comment by Pessimistress** [comment] 2022-08-09 16:03
> I can provide the map to Source by using useMap the same way I tell a click event which map to "use"

I'm not following. If you call `useMap` in your own code you can of course choose what to do with any of the maps. The `Source` component has no knowledge of your application. The logic of this component is to add the source to the direct ancestor that is a `Map`.

**Comment by Pessimistress** [comment] 2022-08-10 14:02
Closing as this is the intended behavior. Please open a feature request if you think it should work otherwise.

**Closed by Pessimistress** 2022-08-10 14:02 UTC

**Comment by tordans** [comment] 2022-08-11 19:26
Thanks for taking the time to explain!
